version: '2'
services:
    jhipsterapp99-app:
        image: jhipsterapp99
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapp99-mysql:3306/jhipsterapp99?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapp99-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapp99-mysql
